config/routes.rb
# コマンド↓ rails g controller コントローラ名　アクション名
# アクション名を指定することで関連するファイルやコードを一度で全て作成できる
# モデルを扱うコントローラでは、データを操作するためのアクションを定義するのが一般的
# new index show edit 等　create update destroyはviewが必要ないアクションのため省略

Rails.application.routes.draw do
  get '/top' => 'homes#top'
  resources :lists
  #resourcesメソッドは、ルーティングを一括して自動生成してくれる機能 
  # lists コントローラの同じ名前のアクションに紐づく形で、以下のルーティングを自動生成してくれる
  
  
  # get 'lists/new'
# フォームを記述したビューを表示するためのルーティング
  # post 'lists' => 'lists#create'
# データを追加（保存）するためのルーティング
# コントローラ作成時にアクション名を入れていないため自動生成されていない
  # get 'lists' => 'lists#index'
# 一覧画面を表示するためのルーティング
  
  # get 'lists/:id' => 'lists#show',as: 'list'
# 詳細画面を表示するためのルーティング
# どの投稿データを表示するかを判別するために、投稿データのidもurlに含める
# 名前付きルートはasオプションを追加することが設定できる
# 'lists#show'の設定をlistとして利用でき、それをredirect_toやlink_toでも使用することができる
  
  # get 'lists/:id/edit' => 'lists#edit',as: 'edit_list'
# lists/:id/editのように、ルーティングのURLに:idを用いて記述すると、lists/◯◯/editのすべてのURLが対象
  
  # patch 'list/:id' => 'lists#update',as: 'update_list'
# 更新機能のためのアクション
  
  # delete 'list/:id' => 'lists#destroy',as: 'destroy_list'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
# コマンド↓ rails g controller コントローラ名　アクション名 
# アクション名を指定することで関連するファイルやコードを一度で全て作成できる

class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
# コマンド↓ rails g controller コントローラ名　アクション名
# アクション名を指定することで関連するファイルやコードを一度で全て作成できる
# モデルを扱うコントローラでは、データを操作するためのアクションを定義するのが一般的
# new index show edit 等　create update destroyはviewが必要ないアクションのため省略

class ListsController < ApplicationController
  def new
    @list = List.new
    # viewへ渡すためのインスタンス変数「＠list」に空のmodelオブジェクトを生成
    # インスタンス変数は同じ名前のviewでしか使用できない
  end

  def create
  list =  List.new(list_params)
  list.save
  redirect_to list_path(list.id)
  end
  # フォームから送られてくるデータは保存される前にparamusの中に入る
  # ストロングパラメータの記述は、private以下へ
  # paramusで保存を許可したデータをデータべースに保存するためsaveメソッドを実行
  # 保存後、画面の遷移にredirect_to urlを指定する

  def index
    @lists = List.all
  end
  # allとはListモデルがやりとりしているデータべースのテーブルに保存されている全てのレコードをまとめて取得する

  def show
    @list = List.find(params[:id])
  end
  # findメソッドは引数を受け取りidカラムを引数と比べてレコードを取得してくるメソッド
  # ＊引数のparamsはcreateで出てきたものとは別の意味！idカラムから取得するときはparamsの記述が必要

  def edit
    @list = List.find(params[:id])
  end
# 投稿済みデータの編集をするので、保存されているデータが必要。findメソッドを用いてデータを取得

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to list_path(list.id)
  end
# updateアクションでは、データ更新後に更新結果を詳細画面に表示するためshowアクションにリダイレクトさせる
# そのため、新たなビュー作成は不要
# showアクションにリダイレクトするために、引数には必ずidが必要になる
  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to 'lists'
  end
  # データレコードを１件取得
  # destroyメソッドによってテーブルからデータが削除される
  # データ削除後のリダイレクト先は、一覧画面を指す'/lists'（indexアクション）に設定

  private
  def list_params
    params.require(:list).permit(:title,:body,:image)
  end
  #require 送られてきたデータの中からモデル名を指定し、データを絞り込む
  # permit  絞り込んだデータの中から保存を許可するカラムを指定する※カラムの数だけ指定

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<!--コマンド↓ rails g controller コントローラ名　アクション名 -->
<!--アクション名を指定することで関連するファイルやコードを一度で全て作成できる-->
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecondApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>編集画面</h1>
<%= form_with model: @list do |f| %>
<!--esourcesメソッドでルーティングを自動生成するとパスが変更された＊rails routesにて確認、以下変更前-->
<!--< %= form_with model: @list, url: update_list_path(@list.id), method: :patch do |f| %>-->
<h4>タイトル</h4>
<%= f.text_field :title %>

<h4>本文</h4>
<%= f.text_area :body %>

<%= f.submit '保存' %>

<% end %>

app/views/lists/index.html.erb
<!--一覧画面の表示-->

<h1>投稿一覧</h1>

<% @lists.each do |list| %>
<!--eachメソッドはレコードの数だけ繰り返し処理を行う-->

<p>タイトル</p>
<%= link_to list.title, list_path(list.id)  %>
<!--一覧画面から詳細画面へ遷移するリンクの設定-->
<!--link_to 表示させるテキスト,リンク先url[,オプション]-->

<!--<span>< %= list.title % ></span>　3章の範囲-->
<!--list変数.カラム名と記述することでレコードのカラムの内容を表示できる-->
<p>画像</p>
<% if list.image.attached? %>
 <%= image_tag list.image, size: "200x200" %>
<% else %>
 <%= image_tag 'no_image', size: "200x200" %>
<% end %>
<!--image_tagヘルパーを使用し画像の表示-->
<!--list.imageに対して.attached?というimageが存在するかを確認するメソッドを呼び出し-->
<!--attached?は、画像が存在していればtrue、存在していなければfalseを返します。-->

<% end %>

app/views/lists/new.html.erb
<!--投稿フォームの作成-->
<!--form_withは、文字を入力するboxを作成するイメージ-->
<!--モデルとの連携、どのurlへデータを送るのか、どのHTTPメソッドで送るかなどを定義できる-->
<!--ブロック変数「f」にはmodelの情報が含まれている-->
<h1>新規投稿</h1>
<%= form_with model: @list, url: '/lists', method: :post do |f| %>

<h4>タイトル</h4>
<%= f.text_field :title %>

<!--「f」にはListモデルの情報が入っているため、このプロパティ名をtitileとすることで-->
<!--ListモデルにあるtitleカラムとRailsは判別することができ、データベースに保存することができる-->
<!--単一行の場合は、text_fieldを使用 ：titleは保存先を指定。titleに保存される-->

<h4>本文</h4>
<%= f.text_area :body %>

<h4>画像</h4>
<%= f.file_field :image, accept:"image/*" %>
<!--file_fieldはファイルの投稿をするためのフィールドのため、画像ファイル以外の全てのファイルを投稿できてしまう-->
<!--画像ファイルしか投稿できないようにaccept:"image/*" を使用-->

<%= f.submit '投稿' %>

<% end %>

app/views/lists/show.html.erb
<!--詳細画面のの作成-->
<h2>タイトル</h2>

<p><%= @list.title %></p>

<h2>本文</h2>
<p><%= @list.body %></p>

<p>画像</p>
<% if @list.image.attached? %>
 <%= image_tag @list.image, size: "300x300" %>
<% else %>
 <%= image_tag 'no_image', size: "300x300" %>
<% end %>

<%= link_to "編集", edit_list_path(@list.id) %>
<!--詳細画面に編集画面へのリンクを追加-->

<%= link_to "削除", list_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
<!--esourcesメソッドでルーティングを自動生成するとパスが変更された＊rails routesにて確認、以下変更前-->
<!--< % = link_to "削除", destroy_list_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>-->
<!--HTTPメソッドがget以外の場合は、urlだけでなくHTTPメソッドも指定しなければならない-->
<!--data-confirmを用いて削除確認ダイアログも表示されるように設定-->